### PR TITLE
Python 3 port

### PR DESCRIPTION
**Pull request by City-busz**

### CODE REVIEW

**Comment by srevinsaju** [comment]
Reviewed and tested. This removes the python2 deps in Fedora and Arch Linux. 
@quozl please review and merge.

**Comment by quozl** [comment]
Thanks.  The changes looked fine.

I dropped sugar-runner from the Sugar release process several releases ago because it wasn't working and didn't seem to have any users.  We had added support to run Sugar activities from a typical desktop environment instead.  I'll leave merging to anyone who wants to take on release responsibility for it.

**Comment by srevinsaju** [comment]
I might be the only user of `sugar-runner` :joy:. I am willing to maintain it for the sake of my needs :)

**Comment by quozl** [comment]
Thanks.  Go ahead.  https://wiki.sugarlabs.org/go/Development_Team/Release

**Comment by srevinsaju** [comment]
@quozl which would be the next stable release? The wiki seems to be outdated in some parts

**Comment by quozl** [comment]
No date or version number is planned for next stable release.  It can't be planned for a date because we don't know when the Port to Python 3 will be finished.  See [GSoC 2020 Port to Python 3](https://github.com/sugarlabs/GSoC/blob/master/Ideas-2020.md#port-sugar-and-core-activities-to-python-3) for what remains to be done.  It can't be planned for a version number because sometimes people ask for an unstable release.

**Comment by quozl** [comment]
(You might release sugar-runner 0.117 if you have tested it fully with Sugar 0.117).

**Comment by srevinsaju** [comment]
Ok

**Comment by chimosky** [comment]
Fixed in 52f45a7.

**Pull request closed without merging**
